#!/usr/bin/env bash
set -euo pipefail

echo "Blog App - GitHub Push Helper"
echo "=============================="
echo ""
echo "1. Create a new repo at: https://github.com/new"
echo "   Name it: blog-app (public, no README)"
echo ""
echo "2. Then run:"
echo ""
echo "   git remote add origin https://github.com/mahakumar197/blog-app.git"
echo "   git push -u origin main"
echo ""
echo "Or with SSH:"
echo ""
echo "   git remote add origin git@github.com:mahakumar197/blog-app.git"
echo "   git push -u origin main"
echo ""
echo "Current branch:"
git branch --show-current 2>/dev/null || echo "main"
echo ""
echo "Latest commit:"
git log -1 --oneline 2>/dev/null || echo "No commits yet"
